### ISSUE TITLE
It is not possible to upload an xml file.

### ISSUE THREAD

**Issue by eshiol** [widgetfactory/jce-legacy#1]
Problem:

It is not possible to upload an xml file.

The problem occurs because the xml files are checked for html tags (IE XSS bug). 
The post request to administrator/index.php?option=com_jce&view=editor&layout=plugin&plugin=browser returns the error "Uncaught exception: INVALID TAG IN FILE".

Solution:

must be patched in line 914:
components/com_jce/editor/libraries/classes/browser.php
old code in JCE 2.5.2:        if (!preg_match('#.(txt|htm|html)$#i', $file['name'])) {
new:        if (!preg_match('#.(txt|htm|html|xml)$#i', $file['name'])) {

**Comment by ryandemmer** [comment]
Fixed in commit https://github.com/widgetfactory/jce/commit/ce494e56a739e9ec70eedd9daa2329ec72b717b0
