### ISSUE TITLE
Can't uninstall extensions

### ISSUE THREAD

**Issue by esedic** [widgetfactory/jce-legacy#2]
I got an error while trying to uninstall extension in installer view.
Chrome dev tools says:

`Uncaught TypeError: Cannot read property 'task' of null (core.js:1)`

I could uninstall an extension when I added CSS id="adminForm" to form in administrator/components/com_jce/views/installer/tmpl/install.php

Using Joomla 3.4.2 with JCE 2.5.2

**Comment by ryandemmer** [comment]
Fixed in commit https://github.com/widgetfactory/jce/commit/8d9e449e92defc148fc866408c53d952d6e8df62
