### ISSUE TITLE
Image file extension case

### ISSUE THREAD

**Issue by brianteeman** [widgetfactory/jce-legacy#3]
Upload an image named UPPERCASE.JPG and it will be saved as UPPERCASE.jpg

Edit an image (eg crop) uploaded elsehwere called UPPERCASE.JPG and it will be saved as UPPERCASE.jpg

As UPPERCASE.JPG and UPPERCASE.jpg are different files the image edits are not displayed on an existing image

**Comment by brianteeman** [comment]
Double checked and the Joomla media manager is not renaming the file

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/fb0acbe20e09da8251654fcd8bd502dc0a2292f0
