### ISSUE TITLE
Composer install error : Use of undefined constant JPATH_COMPONENT_ADMINISTRATOR

### ISSUE THREAD

**Issue by GlassGruber** [widgetfactory/jce-legacy#4]
Hello there!
I was installing my defacto mandatory component for every Joomla! installation (thanks a lot for your work! ;) ), along with some other extension, via the very handy [Composer plugin](https://github.com/joomlatools/joomla-composer) for Joomla!. 

As mentioned in https://github.com/joomlatools/joomla-composer/issues/16 trying to install your extension via Composer results with this error:

```
[ErrorException]
Use of undefined constant JPATH_COMPONENT_ADMINISTRATOR - assumed 'JPATH_COMPONENT_ADMINISTRATOR'
```

Unfortunately I'm not very experienced in this sort of stuff, any suggestions for this? Thank you!

**Comment by ryandemmer** [comment]
I think these changes should do it - https://github.com/widgetfactory/jce/commit/284699b984eec7eda077306cc7a89c26230b68c4

**Comment by GlassGruber** [comment]
Great now it's working! I downloaded the latest JCE .zip, unpacked, updated the code as you did, repacked and installed flawlessly. I was about to send a PR with a [`composer.json`](http://developer.joomlatools.com/tools/composer/distribution.html) file but noticed that the actual repo is different from the release package (install .xml file and other things are missing) and so the whole thing would not install correctly. 
I'm quite noobish in these things, may I ask how come the repo is "partial"? 
Thanks a lot anyway for your help!
