### ISSUE TITLE
Drag & Drop doesn't work since last JCE Update 2.5.11

### ISSUE THREAD

**Issue by ariouche** [widgetfactory/jce-legacy#6]
Hello, since I've updated to  2.5.11, Drag and Drop feature doesn't work.

Each time I try to drag and Drop an image inside the editor, the html tag src is stripped and instead.
Please see the attached file

![video](https://cloud.githubusercontent.com/assets/5327635/12096708/80a5be50-b317-11e5-9422-72f0c960b3c6.gif)

**Comment by ryandemmer** [comment]
Fixed in https://github.com/widgetfactory/jce/releases/tag/2.5.12
