### ISSUE TITLE
JCE is not loaded in IE 10

### ISSUE THREAD

**Issue by sbruemmer** [widgetfactory/jce-legacy#8]
The editor isn't loaded in IE 10 (emulated through IE 11, but also reported on native installation) under windows. This happens in the backend and the frontend.

The console throws an error _"us" is undefined_ in _tiny_mce.js (2,517)_

I wasn't able to locate the source file in your repository. On active installations this is concerning the file `/components/com_jce/editor/tiny_mce/tiny_mce.js`.

The corresponding code extract is:
`l=l&&/MSIE (\w+)\./.exec(us)[1];`

All other user agent tests in the minified script are performed on the variable `g`.
Changing `l=l&&/MSIE (\w+)\./.exec(us)[1];` to `l=l&&/MSIE (\w+)\./.exec(g)[1];` now is doing the job.

**Comment by ryandemmer** [comment]
A patch is available here - https://www.joomlacontenteditor.net/support/forum/jce-2-5-17-and-2-5-18-without-icons-and-toggle-in-ie10#reply-85684

Fixed in commit - https://github.com/widgetfactory/tinymce/commit/6a2711715ab752f6c64634e1a6d2bdc3ceeea8a6

Will be fixed in JCE 2.5.19

**Comment by sbruemmer** [comment]
Thanks!
